import { ServiceCategory, TechTag, ProjectStatus } from './types'
import type { Service, PortfolioProject, Testimonial } from './types'

export const services: Service[] = [
  {
    slug: 'saas',
    name: 'Desenvolvimento de SaaS',
    description: 'Plataformas SaaS escaláveis do zero, com foco em performance, escalabilidade e UX.',
    longDescription: 'Construímos plataformas SaaS escaláveis do zero até o deploy, com arquitetura moderna, autenticação robusta, billing integrado e painel de admin completo. Do MVP à escala enterprise.',
    icon: '🚀',
    category: ServiceCategory.SAAS,
  },
  {
    slug: 'mobile',
    name: 'Aplicativos Mobile',
    description: 'Apps iOS e Android nativos ou multiplataforma com React Native e Flutter.',
    longDescription: 'Desenvolvemos aplicativos mobile de alta qualidade para iOS e Android, usando React Native ou Flutter. Da prototipagem ao deploy nas lojas, com foco em performance e UX nativa.',
    icon: '📱',
    category: ServiceCategory.MOBILE,
  },
  {
    slug: 'landing-page',
    name: 'Landing Pages e Sites',
    description: 'Sites institucionais e landing pages otimizados para SEO e conversão.',
    longDescription: 'Criamos landing pages e sites institucionais de alta performance, otimizados para SEO, com design profissional e focados em conversão de visitantes em clientes.',
    icon: '🌐',
    category: ServiceCategory.LANDING,
  },
  {
    slug: 'ecommerce',
    name: 'E-commerce',
    description: 'Lojas virtuais completas com gateway de pagamento, estoque e painel de vendas.',
    longDescription: 'Desenvolvemos e-commerces completos com catálogo de produtos, carrinho de compras, gateway de pagamento (Stripe, Mercado Pago), gestão de estoque e painel de vendas.',
    icon: '🛒',
    category: ServiceCategory.ECOMMERCE,
  },
  {
    slug: 'dashboard',
    name: 'Dashboards e Painéis',
    description: 'Dashboards analíticos e painéis administrativos para gestão de negócios.',
    longDescription: 'Construímos dashboards e painéis administrativos intuitivos com gráficos em tempo real, relatórios exportáveis e KPIs customizados para a sua operação.',
    icon: '📊',
    category: ServiceCategory.DASHBOARD,
  },
  {
    slug: 'api',
    name: 'APIs e Integrações',
    description: 'APIs REST e GraphQL robustas, integrações com sistemas externos e automações.',
    longDescription: 'Desenvolvemos APIs REST e GraphQL robustas, integrações com ERPs, CRMs, gateways de pagamento e qualquer sistema externo. Automação de processos via webhook e event-driven.',
    icon: '🔌',
    category: ServiceCategory.API,
  },
  {
    slug: 'automacao-com-ia',
    name: 'Automação com IA',
    description: 'Agentes de IA, chatbots inteligentes e automação de processos com LLMs.',
    longDescription: 'Construímos agentes de IA, chatbots inteligentes e fluxos de automação usando OpenAI, Anthropic e modelos open-source. Aumentamos produtividade e reduzimos custos operacionais.',
    icon: '🤖',
    category: ServiceCategory.AI,
  },
  {
    slug: 'marketplace',
    name: 'Marketplace',
    description: 'Plataformas marketplace com multi-vendor, split de pagamentos e gestão de pedidos.',
    longDescription: 'Desenvolvemos marketplaces completos com cadastro de vendedores, split de pagamentos, gestão de pedidos, avaliações e painel de controle para operadores e vendedores.',
    icon: '🏪',
    category: ServiceCategory.MARKETPLACE,
  },
  {
    slug: 'erp',
    name: 'Sistemas ERP',
    description: 'Sistemas de gestão empresarial sob medida para otimizar sua operação.',
    longDescription: 'Desenvolvemos ERPs sob medida adaptados ao seu processo de negócio: gestão financeira, RH, estoque, produção, CRM e relatórios gerenciais em uma única plataforma.',
    icon: '⚙️',
    category: ServiceCategory.ERP,
  },
  {
    slug: 'chatbot',
    name: 'Chatbots e Atendimento',
    description: 'Chatbots para WhatsApp, Telegram e web com IA para atendimento 24/7.',
    longDescription: 'Criamos chatbots inteligentes para WhatsApp Business, Telegram e web com IA conversacional, integração ao seu CRM e handoff para atendentes humanos quando necessário.',
    icon: '💬',
    category: ServiceCategory.CHATBOT,
  },
  {
    slug: 'consultoria',
    name: 'Consultoria Técnica',
    description: 'Arquitetura de sistemas, code review, tech stack e mentoria para sua equipe.',
    longDescription: 'Oferecemos consultoria técnica para definição de arquitetura, escolha de stack, code review, migração de sistemas legados e mentoria para equipes de desenvolvimento.',
    icon: '🎯',
    category: ServiceCategory.CONSULTORIA,
  },
]

export const portfolioProjects: PortfolioProject[] = [
  {
    id: '1',
    title: 'ClinicaPro',
    description: 'SaaS de gestão para clínicas médicas e odontológicas com agendamento online.',
    category: ServiceCategory.SAAS,
    techs: [TechTag.NEXTJS, TechTag.TYPESCRIPT, TechTag.SUPABASE, TechTag.STRIPE],
    status: ProjectStatus.COMPLETED,
    featured: true,
  },
  {
    id: '2',
    title: 'LogiTrack',
    description: 'Sistema de rastreamento e gestão logística em tempo real para transportadoras.',
    category: ServiceCategory.DASHBOARD,
    techs: [TechTag.REACT, TechTag.NODEJS, TechTag.POSTGRES],
    status: ProjectStatus.COMPLETED,
    featured: true,
  },
  {
    id: '3',
    title: 'ConnectMart',
    description: 'Marketplace B2C de produtos artesanais com split de pagamentos Stripe.',
    category: ServiceCategory.MARKETPLACE,
    techs: [TechTag.NEXTJS, TechTag.STRIPE, TechTag.POSTGRES],
    status: ProjectStatus.IN_PROGRESS,
  },
  {
    id: '4',
    title: 'MindBot',
    description: 'Chatbot de suporte psicológico 24/7 integrado ao WhatsApp Business com GPT-4.',
    category: ServiceCategory.AI,
    techs: [TechTag.NODEJS, TechTag.OPENAI, TechTag.TYPESCRIPT],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '5',
    title: 'FitApp',
    description: 'App mobile de treinos e nutrição com planos personalizados por IA.',
    category: ServiceCategory.MOBILE,
    techs: [TechTag.REACT_NATIVE, TechTag.TYPESCRIPT, TechTag.SUPABASE],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '6',
    title: 'StockWise',
    description: 'ERP de gestão de estoque e compras para PMEs com relatórios automáticos.',
    category: ServiceCategory.ERP,
    techs: [TechTag.REACT, TechTag.PYTHON, TechTag.POSTGRES],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '7',
    title: 'EduFlow',
    description: 'Plataforma LMS para cursos online com videoaulas, quizzes e certificados.',
    category: ServiceCategory.SAAS,
    techs: [TechTag.NEXTJS, TechTag.TYPESCRIPT, TechTag.SUPABASE],
    status: ProjectStatus.IN_PROGRESS,
  },
  {
    id: '8',
    title: 'RentEasy',
    description: 'Marketplace de aluguel de imóveis por temporada com calendário e pagamentos.',
    category: ServiceCategory.MARKETPLACE,
    techs: [TechTag.NEXTJS, TechTag.STRIPE, TechTag.POSTGRES],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '9',
    title: 'SalesBot Pro',
    description: 'Agente de IA para qualificação de leads e follow-up automático no WhatsApp.',
    category: ServiceCategory.AI,
    techs: [TechTag.NODEJS, TechTag.OPENAI, TechTag.TYPESCRIPT],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '10',
    title: 'HealthDesk',
    description: 'Dashboard analítico para clínicas com KPIs de atendimento e faturamento.',
    category: ServiceCategory.DASHBOARD,
    techs: [TechTag.REACT, TechTag.TYPESCRIPT, TechTag.PYTHON],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '11',
    title: 'DeliveryHub',
    description: 'Sistema completo de delivery com app para entregadores e painel de pedidos.',
    category: ServiceCategory.MOBILE,
    techs: [TechTag.REACT_NATIVE, TechTag.NODEJS, TechTag.POSTGRES],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '12',
    title: 'ContaAI',
    description: 'Automação contábil com IA para categorização de despesas e relatórios fiscais.',
    category: ServiceCategory.AI,
    techs: [TechTag.PYTHON, TechTag.OPENAI, TechTag.POSTGRES],
    status: ProjectStatus.IN_PROGRESS,
  },
  {
    id: '13',
    title: 'ShopFlow',
    description: 'E-commerce completo com catálogo dinâmico, estoque e painel de vendas.',
    category: ServiceCategory.ECOMMERCE,
    techs: [TechTag.NEXTJS, TechTag.STRIPE, TechTag.SUPABASE],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '14',
    title: 'SystemForge Landing',
    description: 'Site institucional da SystemForge com blog, portfólio e SEO otimizado.',
    category: ServiceCategory.LANDING,
    techs: [TechTag.NEXTJS, TechTag.TYPESCRIPT, TechTag.TAILWIND],
    status: ProjectStatus.IN_PROGRESS,
  },
  {
    id: '15',
    title: 'TechAPI Gateway',
    description: 'API Gateway centralizado com autenticação JWT, rate limiting e monitoramento.',
    category: ServiceCategory.API,
    techs: [TechTag.NODEJS, TechTag.TYPESCRIPT, TechTag.POSTGRES],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '16',
    title: 'HRConnect',
    description: 'Plataforma RH com recrutamento, onboarding e gestão de colaboradores.',
    category: ServiceCategory.ERP,
    techs: [TechTag.REACT, TechTag.NODEJS, TechTag.POSTGRES],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '17',
    title: 'FlutterStore',
    description: 'App mobile de e-commerce com Flutter para iOS e Android.',
    category: ServiceCategory.MOBILE,
    techs: [TechTag.FLUTTER, TechTag.NODEJS, TechTag.STRIPE],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '18',
    title: 'ChatHelper',
    description: 'Chatbot para suporte ao cliente com escalada para atendente humano.',
    category: ServiceCategory.CHATBOT,
    techs: [TechTag.NODEJS, TechTag.OPENAI, TechTag.TYPESCRIPT],
    status: ProjectStatus.COMPLETED,
  },
  {
    id: '19',
    title: 'InvoiceCloud',
    description: 'SaaS de emissão de NFe e controle financeiro para MEIs e PMEs.',
    category: ServiceCategory.SAAS,
    techs: [TechTag.NEXTJS, TechTag.PYTHON, TechTag.POSTGRES],
    status: ProjectStatus.COMPLETED,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    content: 'A SystemForge entregou o nosso sistema de gestão com qualidade e velocidade que não esperávamos. O processo foi transparente e o resultado superou todas as expectativas.',
    author: 'Carlos Mendes',
    role: 'CEO',
    company: 'ClinicaPro',
  },
  {
    id: '2',
    content: 'Trabalhar com a SystemForge foi transformador para o nosso negócio. Em 3 meses tínhamos um marketplace funcionando com split de pagamentos e toda a infraestrutura pronta.',
    author: 'Ana Oliveira',
    role: 'Fundadora',
    company: 'ConnectMart',
  },
  {
    id: '3',
    content: 'O chatbot desenvolvido pela SystemForge reduziu em 40% o tempo de atendimento da nossa equipe. A integração com o WhatsApp Business foi perfeita.',
    author: 'Roberto Costa',
    role: 'Diretor de Operações',
    company: 'TechCorp Brasil',
  },
  {
    id: '4',
    content: 'A metodologia deles é impecável. Cada etapa documentada, entregas pontuais e código limpo que nossa equipe consegue dar manutenção. Recomendo sem hesitar.',
    author: 'Fernanda Souza',
    role: 'CTO',
    company: 'LogiTrack',
  },
]
